### ISSUE TITLE
Mumble integration issue on mac

### ISSUE THREAD

**Issue by mlgprokillz** [GeheimagentNr1/MumbleIntegration#1]
In the config, When auto connect is on, i would either freeze on a loading world screen or it freezes up on a chunk.
I turned off auto connect on config, i was able to join the server but proximity chat would not work.

[latest.log](https://github.com/GeheimagentNr1/MumbleIntegration/files/6094842/latest.log)
Running on MC Version 1.16.4 and Forge 35.1.36
Using an apple computer. Mac version: macOS Mojave 10.14.6

**Comment by iMahco** [comment]
To add to this,

> [01:25:08] [Thread-1/INFO]: [address] = IP:25567
> was fixed into just [IP] incase that was the issue, still no luck.

manually connecting into the proper mumble server, after disabling auto-connect and receiving **Linked** message also did not work with positional audio. We're dumbfounded and thinking this might be a mac issue somehow?? Unsure, 3 other windows-clients can connect and use proximity just fine.

**Comment by GeheimagentNr1** [comment]
There are separate config properties for "address" and "port".
The "address" property value has to be the URL or the IP address of the mumble server.
The "port" has to be the port of the mumble server.

Positional audio should work an every Windows and POSIX operating systems.
Is the "Link v1.2.0" in the Mumble client enabled?
Is the option "Link to Game and Transmit Position" in Settings > Plugins and the option "Positional Audio" in Settings > Audio Output enabled?
Is  the Positional Audio "Minimum Volume" at Settings > Audio Output > Positional Audio at 0%?

**Comment by mlgprokillz** [comment]
The problem isn't necessarily that it doesn't work and we've done all those settings. Although, when i try to join an SMP, the game would freeze. Turning off auto connect and removing the mod allows me to connect to the server just fine.

<img width="875" alt="Screen Shot 2021-03-06 at 10 08 40 PM" src="https://user-images.githubusercontent.com/80145480/110227649-8ed7d300-7ec8-11eb-88fb-c15cb108f415.png">

Again, im doing this on Mac computer.
Opening mumble before MC and turning off auto connect allows me to join the server just fine and on the mumble chat says the mod is linked. But, it doesnt say that mumble is linked on MC chat and positional audio doesnt work.

**Comment by GeheimagentNr1** [comment]
In MC there is only a message in the log, if mumble is linked or unlinked.
Please try what happens, if you enter this link to your browser:
mumble://158.69.123.124:64738
Only if mumble opens and connect to your mumble server the Mumble Integration Mod will be able to auto connect to mumble.

**Comment by mlgprokillz** [comment]
I tried the link and it asked me whether i want to open the mumble app.

**Comment by GeheimagentNr1** [comment]
Is mumble able to connect to the server, if you use this link in the browser?
mumble://158.69.123.124:64738/Minecraft
If so, the auto connect should also work.
